# Generated by Django 4.2.2 on 2023-06-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefunction', '0008_featurepost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurepost',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除'), (2, '草稿')], default=1),
        ),
    ]
