# Generated by Django 4.2.2 on 2023-06-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='STUCMS', max_length=32, verbose_name='首页标题')),
                ('ad_title', models.CharField(default='STUCMS', max_length=32, verbose_name='公众号标题')),
                ('ad_image', models.CharField(default="{% static 'images/stu.png' %}", max_length=999, verbose_name='公众号图片URL')),
            ],
        ),
    ]
